### ISSUE TITLE
FileNotFoundError in Demicode Library When Running in Pyenv Virtualenv on macOS

### ISSUE THREAD

**Issue by yohann84L** [apparebit/demicode#1]
Hello, I was trying to use your library but I am facing the following issue:
```
Demicode encountered an unexpected error. For details, please see the
exception trace below. If you can exclude your system as cause, please
file an issue at https://github.com/apparebit/demicode/issues.
Traceback (most recent call last):

  File "~/.pyenv/versions/3.11.2/envs/***/lib/python3.11/site-packages/demicode/tool.py", line 345, in run
    return process(options, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/.pyenv/versions/3.11.2/envs/***/lib/python3.11/site-packages/demicode/tool.py", line 366, in process
    ucd = UnicodeCharacterDatabase(
          ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/.pyenv/versions/3.11.2/envs/***/lib/python3.11/site-packages/demicode/db/ucd.py", line 215, in __init__
    self._mirror = mirror = Mirror(root, version, tick)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/.pyenv/versions/3.11.2/envs/***/lib/python3.11/site-packages/demicode/db/mirror.py", line 633, in __init__
    self._manifest = Manifest.setup(root or self.default_path(), tick)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/.pyenv/versions/3.11.2/envs/***/lib/python3.11/site-packages/demicode/db/mirror.py", line 377, in setup
    .sync(previous, tick)
     ^^^^^^^^^^^^^^^^^^^^

  File "~/.pyenv/versions/3.11.2/envs/***/lib/python3.11/site-packages/demicode/db/mirror.py", line 334, in sync
    versions = file_manager.scan_retrieved_versions()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "~/.pyenv/versions/3.11.2/envs/***/lib/python3.11/site-packages/demicode/db/mirror.py", line 541, in scan_retrieved_versions
    for entry in self.mirror.iterdir():

  File "~/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: '~/Library/Caches/demicode/ucd'
```

I am using demicode in warp using a pyenv virtualenv.

**Comment by apparebit** [comment]
Oops, I forgot to create the cache directory when it doesn't exist. This should be fixed in [v1.3](https://github.com/apparebit/demicode/releases/tag/v1.3), which I just released.
